image:
- Visual Studio 2019
- macOS
- Ubuntu

skip_branch_with_pr: true
stack: python 3.10

environment:
  GITHUB_TOKEN:
    secure: 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

install:
- pip install -r requirements.txt

build_script:
- flet pack main.py --name convWebp --product-name convWebp --product-version "1.0" --copyright "Copyright (c) 2024 samenoko"

test: off

# Publish artifacts to GitHub Releases on "tag" builds
deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  on:
    APPVEYOR_REPO_TAG: true

#
#   Windows package
# 
for:
-
  matrix:
    only:
    - image: Visual Studio 2019

  after_build:
  - 7z a convWebp-windows.zip %CD%\dist\*.exe

  artifacts:
  - path: convWebp-windows.zip

#
#   macOS package
# 
-
  matrix:
    only:
    - image: macOS

  after_build:
  - tar -czvf convWebp-macos.tar.gz -C dist counter.app

  artifacts:
  - path: convWebp-macos.tar.gz
