name: Build and Release Flet App

on:
  push:
    branches:
      - main

env:
  APP_NAME: "convWebp"  # グローバルなアプリ名

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Package the app
        run: |
          flet pack main.py --name $APP_NAME --product-name $APP_NAME --product-version "1.0" --copyright "Copyright (c) 2024 samenoko"

      - name: Create ZIP for Windows
        run: |
          cd dist
          zip -r "${APP_NAME}-Windows.zip" "${APP_NAME}.exe"

      - name: Upload Windows Release using gh
        run: |
          gh release create v1.0.0 "${APP_NAME}-Windows.zip" --title "Release v1.0.0" --notes "First release of ${APP_NAME} for Windows."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-mac:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Package the app
        run: |
          flet pack main.py --name $APP_NAME --product-name $APP_NAME --product-version "1.0" --copyright "Copyright (c) 2024 samenoko"

      - name: Create ZIP for macOS
        run: |
          cd dist
          zip -r "${APP_NAME}-macOS.zip" "${APP_NAME}.app"

      - name: Upload macOS Release using gh
        run: |
          gh release create v1.0.0 "${APP_NAME}-macOS.zip" --title "Release v1.0.0" --notes "First release of ${APP_NAME} for macOS."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
